server type: null
offer: chat
chat offer:
  - "You can use the "
  - text: /source
    italic: true
    clickEvent:
      action: run_command
      value: /source
  - " command to see the source code of this server"
sources: # case sensitive
  CraftBukkit: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit
  Spigot: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot
  Paper: https://github.com/PaperMC/Paper