server type: null
offer:
  type: chat
  chat:
    - "You can use the "
    - text: /source
      italic: true
      clickEvent:
        action: run_command
        value: /source
    - " command to see the source code of this server"
  book:
    title: Source Code
    author: sfinnqs
    first page:
      - "This book contains links to the source code of this server, including all plugins running on it.\n\nYou can also use the "
      - text: /source
        italic: true
        clickEvent:
          action: run_command
          value: /source
      - " command to see the same links."
sources: # case sensitive
  CraftBukkit: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit
  Spigot: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot
  Paper: https://github.com/PaperMC/Paper
