name: Source
version: ${project.version}
main: org.sfinnqs.source.SourcePlugin
api-version: "1.14"
commands:
  source:
    description: Locate the source code of plugins on the server
    usage: /<command> [plugin]
  sourceadmin:
    description: Administrate the Source plugin
    permission: source.admin
    permission-message: §You do not have permission to administrate the Source plugin
    usage: /<command> <reload | add | remove>
permissions:
  source.admin:
    description: Allows use of the "/sourceadmin" command
    default: op
